<?php

declare(strict_types=1);

return [
    'navigation' => [
        'name' => 'Menus',
        'plural' => 'Menus',
        'group' => [
            'name' => 'Content Management',
            'description' => 'Manage website navigation menus',
        ],
        'label' => 'Menus',
        'sort' => '20',
        'icon' => 'heroicon-o-bars-3',
    ],
    'fields' => [
        'id' => [
            'label' => 'ID',
            'placeholder' => 'Menu ID',
            'description' => 'Unique menu identifier',
            'helper_text' => 'Automatically generated by the system',
        ],
        'name' => [
            'label' => 'Name',
            'placeholder' => 'Menu name',
            'tooltip' => 'Menu identifier name',
            'description' => 'Main menu name',
            'helper_text' => 'The name helps identify the menu in the system',
        ],
        'slug' => [
            'label' => 'Slug',
            'placeholder' => 'menu-slug',
            'tooltip' => 'URL-friendly identifier for menu',
            'description' => 'Menu URL identifier',
            'helper_text' => 'The slug determines the menu identifier',
        ],
        'type' => [
            'label' => 'Type',
            'placeholder' => 'Select type',
            'tooltip' => 'Menu type',
            'description' => 'Menu type for navigation',
            'helper_text' => 'The type determines the menu behavior',
            'options' => [
                'main' => 'Main',
                'footer' => 'Footer',
                'sidebar' => 'Sidebar',
            ],
        ],
        'status' => [
            'label' => 'Status',
            'placeholder' => 'Menu status',
            'tooltip' => 'Menu publication status',
            'description' => 'Current menu status (active, inactive, draft)',
            'helper_text' => 'Control menu visibility',
            'options' => [
                'active' => 'Active',
                'inactive' => 'Inactive',
                'draft' => 'Draft',
            ],
        ],
        'toggleColumns' => [
            'label' => 'Show/Hide Columns',
            'placeholder' => 'Manage column visibility',
            'tooltip' => 'Control column visibility',
            'description' => 'Action to show or hide table columns',
            'helper_text' => 'Customize table display',
        ],
        'message' => [
            'label' => 'Message',
            'placeholder' => 'Enter a message',
            'tooltip' => 'Informational message',
            'description' => 'System message or communication',
            'helper_text' => 'Message to display to user',
        ],
        'openFilters' => [
            'label' => 'Open Filters',
            'placeholder' => 'Click to open filters',
            'tooltip' => 'Show available filters',
            'description' => 'Action to open filter panel',
            'helper_text' => 'Show available filter options',
        ],
        'applyFilters' => [
            'label' => 'Apply Filters',
            'placeholder' => 'Click to apply',
            'tooltip' => 'Apply selected filters',
            'description' => 'Action to apply configured filters',
            'helper_text' => 'Filter results based on selected criteria',
        ],
        'resetFilters' => [
            'label' => 'Reset Filters',
            'placeholder' => 'Click to reset',
            'tooltip' => 'Remove all applied filters',
            'description' => 'Action to remove all active filters',
            'helper_text' => 'Restore display of all records',
        ],
        'reorderRecords' => [
            'label' => 'Reorder Elements',
            'placeholder' => 'Drag to reorder',
            'tooltip' => 'Reorder element sequence',
            'description' => 'Action to modify record order',
            'helper_text' => 'Change menu display order',
        ],
        'delete' => [
            'label' => 'Delete',
            'placeholder' => 'Confirm deletion',
            'tooltip' => 'Permanently remove element',
            'description' => 'Action to delete selected record',
            'helper_text' => 'Permanently delete menu from system',
        ],
        'title' => [
            'label' => 'Title',
            'placeholder' => 'Enter title',
            'tooltip' => 'Menu title',
            'description' => 'Main menu title',
            'helper_text' => 'The title will be visible in navigation',
        ],
    ],
    'actions' => [
        'create' => [
            'label' => 'Create Menu',
            'tooltip' => 'Create a new menu',
            'description' => 'Action to create a new menu',
        ],
        'edit' => [
            'label' => 'Edit Menu',
            'tooltip' => 'Edit existing menu',
            'description' => 'Action to edit the menu',
        ],
        'delete' => [
            'label' => 'Delete Menu',
            'tooltip' => 'Delete the menu',
            'description' => 'Action to delete the menu',
        ],
        'sort' => [
            'label' => 'Sort Items',
            'tooltip' => 'Sort menu items',
            'description' => 'Action to sort menu items',
        ],
        'add_item' => [
            'label' => 'Add Item',
            'tooltip' => 'Add new item to menu',
            'description' => 'Action to add an item to the menu',
        ],
    ],
    'messages' => [
        'created' => 'Menu created successfully',
        'updated' => 'Menu updated successfully',
        'deleted' => 'Menu deleted successfully',
        'sorted' => 'Menu items sorted successfully',
        'item_added' => 'Item added successfully',
    ],
    'validation' => [
        'name_required' => 'The name is required',
        'slug_unique' => 'The slug must be unique',
        'type_in' => 'The type must be one of: main, footer, sidebar',
    ],
    'model' => [
        'label' => 'Menu Model',
        'tooltip' => 'Menu data model',
        'description' => 'Representation of the menu model in the system',
    ],
];
