<?php

declare(strict_types=1);

return [
    'navigation' => [
        'name' => 'Page Contents',
        'plural' => 'Page Contents',
        'group' => [
            'name' => 'Content Management',
            'description' => 'Manage page contents of the website',
        ],
        'label' => 'Page Contents',
        'sort' => '87',
        'icon' => 'heroicon-o-document-text',
    ],
    'fields' => [
        'id' => [
            'label' => 'ID',
            'placeholder' => 'Page content ID',
            'description' => 'Unique content identifier',
            'helper_text' => 'Automatically generated by the system',
        ],
        'name' => [
            'label' => 'Name',
            'placeholder' => 'Content name',
            'description' => 'Content identifier name',
            'helper_text' => 'The name helps identify the content',
        ],
        'slug' => [
            'label' => 'Slug',
            'placeholder' => 'Page content slug',
            'description' => 'URL-friendly identifier for content',
            'helper_text' => 'The slug determines the content URL',
        ],
        'blocks' => [
            'label' => 'Blocks',
            'placeholder' => 'Content blocks',
            'description' => 'Page content blocks',
            'helper_text' => 'Configure content blocks to display',
        ],
        'created_at' => [
            'label' => 'Creation Date',
            'placeholder' => 'Creation date and time',
            'description' => 'Content creation date and time',
            'helper_text' => 'Automatically generated by the system',
        ],
        'updated_at' => [
            'label' => 'Last Updated',
            'placeholder' => 'Last update date and time',
            'description' => 'Date and time of last update',
            'helper_text' => 'Automatically updated on every change',
        ],
        'created_by' => [
            'label' => 'Created By',
            'placeholder' => 'Created by',
            'description' => 'User who created the content',
            'helper_text' => 'Identifies the content author',
        ],
        'updated_by' => [
            'label' => 'Updated By',
            'placeholder' => 'Updated by',
            'description' => 'User who updated the content',
            'helper_text' => 'Identifies the last author of changes',
        ],
        'toggleColumns' => [
            'label' => 'Show/Hide Columns',
            'placeholder' => 'Manage column visibility',
            'tooltip' => 'Control column visibility',
            'description' => 'Action to show or hide table columns',
            'helper_text' => 'Customize table display',
        ],
        'reorderRecords' => [
            'label' => 'Reorder Elements',
            'placeholder' => 'Drag to reorder',
            'tooltip' => 'Reorder element sequence',
            'description' => 'Action to modify record order',
            'helper_text' => 'Change content display order',
        ],
        'resetFilters' => [
            'label' => 'Reset Filters',
            'placeholder' => 'Click to reset',
            'tooltip' => 'Remove all applied filters',
            'description' => 'Action to remove all active filters',
            'helper_text' => 'Restore display of all records',
        ],
        'applyFilters' => [
            'label' => 'Apply Filters',
            'placeholder' => 'Click to apply',
            'tooltip' => 'Apply selected filters',
            'description' => 'Action to apply configured filters',
            'helper_text' => 'Filter results based on selected criteria',
        ],
        'openFilters' => [
            'label' => 'Open Filters',
            'placeholder' => 'Click to open filters',
            'tooltip' => 'Show available filters',
            'description' => 'Action to open filter panel',
            'helper_text' => 'Show available filter options',
        ],
        'delete' => [
            'label' => 'Delete',
            'placeholder' => 'Confirm deletion',
            'tooltip' => 'Permanently remove element',
            'description' => 'Action to delete selected record',
            'helper_text' => 'Permanently delete content from system',
        ],
        'edit' => [
            'label' => 'Edit',
            'placeholder' => 'Click to edit',
            'tooltip' => 'Edit selected element',
            'description' => 'Action to edit record',
            'helper_text' => 'Open content edit form',
        ],
        'view' => [
            'label' => 'View',
            'placeholder' => 'Click to view',
            'tooltip' => 'View element details',
            'description' => 'Action to view record',
            'helper_text' => 'Show complete content details',
        ],
    ],
    'actions' => [
        'view' => [
            'label' => 'View Content',
            'tooltip' => 'View content details',
            'description' => 'Action to view the content',
        ],
        'create' => [
            'label' => 'Create Content',
            'tooltip' => 'Create new content',
            'description' => 'Action to create new content',
        ],
        'edit' => [
            'label' => 'Edit Content',
            'tooltip' => 'Edit existing content',
            'description' => 'Action to edit the content',
        ],
        'delete' => [
            'label' => 'Delete Content',
            'tooltip' => 'Delete the content',
            'description' => 'Action to delete the content',
        ],
        'activeLocale' => [
            'label' => 'Active Language',
            'tooltip' => 'Current interface language',
            'description' => 'Currently active language for user',
        ],
    ],
    'messages' => [
        'created' => 'Content created successfully',
        'updated' => 'Content updated successfully',
        'deleted' => 'Content deleted successfully',
    ],
    'validation' => [
        'name_required' => 'The name is required',
        'slug_unique' => 'The slug must be unique',
        'blocks_required' => 'Content blocks are required',
    ],
    'model' => [
        'label' => 'Page Content',
        'tooltip' => 'Page content data model',
        'description' => 'Representation of the page content model in the system',
    ],
];
