name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step per il checkout del repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step per aggiornare le dipendenze PHP
      - name: Update Dependencies
        run: composer update

      # Step per validare i file composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      # Step per installare le dipendenze PHP
      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      # Step per installare le dipendenze Node.js
      - name: Install Node Dependencies
        run: npm install

      # Step per eseguire la build di produzione
      - name: Build Production Assets
        run: npm run prod

      # Step per impostare il CNAME per GitHub Pages
      - name: Create CNAME File
        run: echo "laraxot.github.io/doc_activity" > ./build_production/CNAME

      # Step per il deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build_production
          clean: true
